import type { Product } from '@/entities/product';

export const HOME_VESHALA_PRODUCTS: Product[] = [
    {
        title: 'Вешало HOME с 1-ой полкой',
        description: 'Арт: HOME-01',
        size: '910 × 330 × 1500 мм',
        price: 2330,
        imageSrc: '/veshala/veshalo-home-1-polka.jpg',
    },
    {
        title: 'Вешало HOME с 2-мя полками',
        description: 'Арт: HOME-02',
        size: '910 × 330 × 1500 мм',
        price: 2650,
        imageSrc: '/veshala/veshalo-home-2-polki.jpg',
    },
    {
        title: 'Вешало HOME с 3-мя полками',
        description: 'Арт: HOME-03',
        size: '1000 × 330 × 1500 мм',
        price: 3400,
        imageSrc: '/veshala/veshalo-home-3-polki.jpg',
    },
    {
        title: 'Вешало HOME с 5-ю полками',
        description: 'Арт: HOME-04',
        size: '1000 × 330 × 1500 мм',
        price: 3800,
        imageSrc: '/veshala/veshalo-home-5-polok.jpg',
    },
];

export const HOME_STELLAZH_PRODUCTS: Product[] = [
    {
        title: 'Стеллаж HOME узкий',
        description: 'Арт: HOME-01s',
        size: '400 × 330 × 1260 мм',
        price: 3100,
        imageSrc: '/veshala/stelazh-home-uzkiy.png',
    },
    {
        title: 'Стеллаж HOME широкий',
        description: 'Арт: HOME-02s',
        size: '900 × 330 × 1260 мм',
        price: 4100,
        imageSrc: '/veshala/stelaz-home-shirokiy.png',
    },
];

export const FLOOR_VESHALA_PRODUCTS: Product[] = [
    {
        title: 'Вешало для одежды ST 001',
        description: 'Цвет: хром / чёрный',
        size: 'Длина 900–1450 мм, высота 1570 мм',
        price: 3300,
        imageSrc: '/veshala/veshalo-st-001.jpg',
    },
    {
        title: 'Вешало для одежды ST 002',
        description: 'Цвет: хром / чёрный',
        size: 'Длина 900–1200 мм, высота 2015 мм',
        price: 4000,
        imageSrc: '/veshala/veshalo-st-002.jpg',
    },
    {
        title: 'Вешало для одежды ST 003 D',
        description: 'Цвет: чёрный',
        size: 'Длина 1200–2100 мм, высота 750–2000 мм, ширина 500 мм',
        price: 4200,
        imageSrc: '/veshala/veshalo-st-003-d.jpg',
    },
    {
        title: 'Вешало для одежды ST 005',
        description: 'Цвет: хром / чёрный',
        size: 'Длина 900–1450 мм, высота 1570 мм',
        price: 5800,
        imageSrc: '/veshala/veshalo-st-005.jpg',
    },
    {
        title: 'Вешало для одежды ST 010 R50R',
        description: 'Цвет: хром, регулируемая стойка',
        size: 'Длина 1500 мм, высота 1250–2000 мм',
        price: 12040,
        imageSrc: '/veshala/veshalo-st-010-r50r.jpg',
    },
    {
        title: 'Вешало для одежды ST 011 R50R',
        description: 'Цвет: хром',
        size: 'Длина 1500 мм, высота 1250–2000 мм',
        price: 13060,
        imageSrc: '/veshala/veshalo-st-011-r50r.jpg',
    },
    {
        title: 'Вешало для одежды ST 01',
        description: 'Сборно-разборное',
        size: 'Длина 1200 мм, высота 1500 мм, ширина 525 мм',
        price: 2450,
        imageSrc: '/veshala/veshalo-st-01.jpg',
    },
    {
        title: 'Вешало для одежды ST 01K',
        description: 'Сборно-разборное, на колёсах',
        size: 'Длина 1200 мм, высота 1500 мм, ширина 525 мм',
        price: 2750,
        imageSrc: '/veshala/veshalo-st-01-k.jpg',
    },
    {
        title: 'Вешало для одежды D1-023-C',
        description: 'Цвет: хром',
        size: 'Длина 1200–2000 мм, высота 750–1500 мм',
        price: 2900,
        imageSrc: '/veshala/veshalo-d1-023-c.jpg',
    },
    {
        title: 'Вешало для одежды D1-025-C',
        description: 'Цвет: хром',
        size: 'Длина 1200–2000 мм, высота 850–1500 мм',
        price: 3650,
        imageSrc: '/veshala/veshalo-d1-025-c.jpg',
    },
    {
        title: 'Вешало для одежды D3-061',
        description: 'Цвет: хром + чёрный',
        size: 'Ширина 800 мм, высота 1150–1900 мм',
        price: 3900,
        imageSrc: '/veshala/veshalo-d3-061.jpg',
    },
    {
        title: 'Вешало для одежды D3-064-C',
        description: 'Цвет: хром',
        size: 'Ширина 1200 мм, высота 1300–1850 мм',
        price: 4900,
        imageSrc: '/veshala/veshalo-d3-064-c.jpg',
    },
    {
        title: 'Вешало П-образное D1-020',
        description: 'Цвет: хром',
        size: 'Длина 750–1600 мм, высота 1700 мм, ширина 440 мм',
        price: 3300,
        imageSrc: '/veshala/veshalo-d1-020.jpg',
    },
    {
        title: 'Вешало «Фонтан» D2-008',
        description: 'Цвет: сталь хромированная',
        size: 'Длина 1200–2100 мм, высота 750–1800 мм, ширина 500 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/veshala/veshalo-d2-008.jpg',
    },
    {
        title: 'Вешало для одежды ST 105 L',
        description: 'Цвет: серый металлик / чёрный',
        size: 'Длина 1200 мм, высота 1200–1700 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/veshala/veshalo-st-105-l.jpg',
    },
    {
        title: 'Вешало для одежды ST 107 L',
        description: 'Цвет: серый металлик / чёрный',
        size: 'Длина 1200 мм, высота 1200–1700 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/veshala/veshalo-st-107-l.jpg',
    },
    {
        title: 'Вешало пристенное AST-11/1200',
        description: 'Черный муар. Дополнительная секция L=1200 — 2 619 руб.',
        size: '1200 × 300 × 2300 мм',
        price: 3450,
        imageSrc: '/veshala/veshalo-ast-11-1200.jpeg',
    },
    {
        title: 'Вешало напольное двойное AST-02',
        description: 'Цвет: чёрный муар',
        size: '1200 × 600 × 1500 мм',
        price: 5900,
        imageSrc: '/veshala/veshalo-ast-02.jpeg',
    },
    {
        title: 'Вешало напольное одинарное AST-01',
        description: 'Цвет: чёрный муар',
        size: '1200 × 525 × 1500 мм',
        price: 3500,
        imageSrc: '/veshala/veshalo-ast-01.jpeg',
    },
    {
        title: 'Демонстрационный стол ASTS 900×450×300',
        description: 'Черный муар, металлический каркас',
        size: '900 × 450 × 300 мм',
        price: 3550,
        imageSrc: '/veshala/veshalo-asts.jpg',
    },
    {
        title: 'Демонстрационный стол ASTS 1200×450×600',
        description: 'Черный муар, металлический каркас',
        size: '1200 × 450 × 600 мм',
        price: 4600,
        imageSrc: '/veshala/veshalo-asts.jpg',
    },
    {
        title: 'Вешало напольное 5MR-11',
        description: 'Цвет: чёрный муар, регулируемое, на роликах',
        size: 'Длина 1800 мм, высота 1250–2000 мм, ширина 500 мм',
        price: 3190,
        imageSrc: '/veshala/veshalo-5mr-11.png',
    },
    {
        title: 'Вешало напольное одинарное 5MR-01',
        description: 'Цвет: хром, регулируемое, на роликах',
        size: 'Длина 1200 мм, высота 1250–2000 мм, ширина 500 мм',
        price: 4250,
        imageSrc: '/veshala/veshalo-5mr-01.png',
    },
    {
        title: 'Вешало П-образное «Лыжи» D1-007',
        description: 'Цвет: чёрный + хром, две перекладины',
        size: 'Длина 1200–2100 мм, высота 750–2000 мм, ширина 500 мм',
        price: 3150,
        imageSrc: '/veshala/veshalo-d1-007.jpg',
    },
    {
        title: 'Вешало напольное одинарное 5M-01',
        description: 'Цвет: хром, на роликах',
        size: 'Длина 1200 мм, высота 1650 мм, ширина 500 мм',
        price: 2780,
        imageSrc: '/veshala/veshalo-5m-01.png',
    },
    {
        title: 'Вешало П-образное с шариками D1-031',
        description: 'Регулируемая высота',
        size: 'Высота 2000 мм, длина 1200–2100 мм, глубина 440 мм',
        price: 2850,
        imageSrc: '/veshala/veshalo-d1-031.jpg',
    },
    {
        title: 'Вешало трёхрожковое D3-063-3',
        description: 'Три рожка, цвет: хром',
        size: 'Высота 1800 мм, ширина 700 мм',
        price: 4230,
        imageSrc: '/veshala/veshalo-d3-063-3.jpg',
    },
    {
        title: 'Вешало четырёхрожковое D3-063-4',
        description: 'Четыре рожка, цвет: хром',
        size: 'Высота 1800 мм, ширина 700 мм',
        price: 4450,
        imageSrc: '/veshala/veshalo-d3-063-4.jpg',
    },
    {
        title: 'Вешало четырёхрожковое ST 030 R50R',
        description: 'Цвет: хром',
        size: 'Высота 1400–1800 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/veshala/veshalo-st-030-r50r.jpg',
    },
    {
        title: 'Вешало для шляп D3-042 B',
        description: 'Цвет: хром, кронштейны для головных уборов',
        size: 'Размер: уточняйте при заказе',
        price: 3670,
        imageSrc: '/veshala/veshalo-d-3-042-b.jpg',
    },
    {
        title: 'Вешало П-образное Z1002',
        description: 'Цвет: хром',
        size: 'Высота 750–1490 мм, длина 900–1760 мм',
        price: 2600,
        imageSrc: '/veshala/veshalo-z1002.jpg',
    },
];
