import type { Product } from '@/entities/product';

export const CENNIKODERZHATELI_PRODUCTS: Product[] = [
    {
        title: 'Ценникодержатель на крючок',
        description: 'Арт: ОЦК-40-60',
        size: '40 × 60 мм',
        price: 11,
        imageSrc: '/orgsteklo/cennikoderzhateli/ock-40-60.jpg',
    },
    {
        title: 'Подставка под ценник',
        description: 'Арт: ОПЛ-40-20-30',
        size: '40 × 20 × 30 мм',
        price: 22,
        imageSrc: '/orgsteklo/cennikoderzhateli/opl-40-20-30.jpg',
    },
    {
        title: 'Подставка под ценник',
        description: 'Арт: ОПЛ-60-25-40',
        size: '60 × 25 × 40 мм',
        price: 30,
        imageSrc: '/orgsteklo/cennikoderzhateli/opl-60-25-40.jpg',
    },
    {
        title: 'Подставка под ценник',
        description: 'Арт: ОПЛ-70-30-45',
        size: '70 × 30 × 45 мм',
        price: 39,
        imageSrc: '/orgsteklo/cennikoderzhateli/opl-70-30-45.jpg',
    },
    {
        title: 'Подставка под ценник',
        description: 'Арт: ОПЛ-60-45-75',
        size: '60 × 45 × 75 мм',
        price: 46,
        imageSrc: '/orgsteklo/cennikoderzhateli/opl-60-45-75.jpg',
    },
    {
        title: 'Подставка под ценник',
        description: 'Арт: ОПЛ-90-35-55',
        size: '90 × 35 × 55 мм',
        price: 51,
        imageSrc: '/orgsteklo/cennikoderzhateli/opl-90-35-55.jpg',
    },
    {
        title: 'Подставка под ценник',
        description: 'Арт: ОПЛ-60-55-95',
        size: '60 × 55 × 95 мм',
        price: 58,
        imageSrc: '/orgsteklo/cennikoderzhateli/opl-60-55-95.jpg',
    },
    {
        title: 'Подставка под ценник',
        description: 'Арт: ОПЛ-80-55-95',
        size: '80 × 55 × 95 мм',
        price: 83,
        imageSrc: '/orgsteklo/cennikoderzhateli/opl-80-55-95.jpg',
    },
    {
        title: 'Подставка под ценник',
        description: 'Арт: ОП-40-20-35',
        size: '40 × 20 × 35 мм',
        price: 12,
        imageSrc: '/orgsteklo/cennikoderzhateli/op-40-20-35.jpg',
    },
    {
        title: 'Подставка под ценник',
        description: 'Арт: ОП-60-25-45',
        size: '60 × 25 × 45 мм',
        price: 21,
        imageSrc: '/orgsteklo/cennikoderzhateli/op-60-25-45.jpg',
    },
    {
        title: 'Подставка под ценник',
        description: 'Арт: ОП-70-30-45',
        size: '70 × 30 × 45 мм',
        price: 22,
        imageSrc: '/orgsteklo/cennikoderzhateli/op-70-30-45.jpg',
    },
    {
        title: 'Подставка под ценник',
        description: 'Арт: ОП-70-30-55',
        size: '70 × 30 × 55 мм',
        price: 25,
        imageSrc: '/orgsteklo/cennikoderzhateli/op-70-30-55.jpg',
    },
    {
        title: 'Подставка под ценник',
        description: 'Арт: ОП-60-45-85',
        size: '60 × 45 × 85 мм',
        price: 33,
        imageSrc: '/orgsteklo/cennikoderzhateli/op-60-45-85.jpg',
    },
    {
        title: 'Подставка под ценник',
        description: 'Арт: ОП-60-55-105',
        size: '60 × 55 × 105 мм',
        price: 39,
        imageSrc: '/orgsteklo/cennikoderzhateli/op-60-55-105.jpg',
    },
    {
        title: 'Подставка под ценник',
        description: 'Арт: ОП-80-40-105',
        size: '80 × 40 × 105 мм',
        price: 55,
        imageSrc: '/orgsteklo/cennikoderzhateli/op-80-40-105.jpg',
    },
];
