import type { Product } from '@/entities/product';

export const MANEKENY_TORSY_PRODUCTS: Product[] = [
    {
        title: 'Торс мужской T 402',
        description: 'Арт: T 402',
        size: 'Цена включает стандартный комплект',
        price: 260,
        imageSrc: '/manekeny-portnovskie/tors-t-402.jpg',
    },
    {
        title: 'Торс женский T 401',
        description: 'Арт: T 401',
        size: 'Базовая комплектация',
        price: 250,
        imageSrc: '/manekeny-portnovskie/tors-t-401.jpg',
    },
    {
        title: 'Торс женский T 403',
        description: 'Арт: T 403',
        size: 'Базовая комплектация',
        price: 490,
        imageSrc: '/manekeny-portnovskie/tors-t-403.jpg',
    },
    {
        title: 'Ноги женские / мужские Н 201',
        description: 'Арт: Н 201',
        size: 'Универсальный размер',
        price: 495,
        imageSrc: '/manekeny-portnovskie/nogi-h-201.jpg',
    },
    {
        title: 'Торс женский «Алиссия»',
        description: 'Цвета: карамель, чёрный, серый',
        size: 'Материал: пластик',
        price: null,
        priceLabel: '250 / 265 / 290 руб.',
        imageSrc: '/manekeny-portnovskie/tors-allisia.jpg',
    },
    {
        title: 'Торс мужской «Карон»',
        description: 'Арт: «Карон»',
        size: 'Материал: пластик',
        price: 380,
        imageSrc: '/manekeny-portnovskie/tors-karon.jpg',
    },
    {
        title: 'Торс женский «Света»',
        description: 'Цвета: чёрный, серый, белый',
        size: 'Материал: пластик',
        price: null,
        priceLabel: '640 / 660 / 670 руб.',
        imageSrc: '/manekeny-portnovskie/tors-sveta.jpg',
    },
    {
        title: 'Манекен детский ТД-103',
        description: 'Арт: ТД-103',
        size: 'В: 570 мм, Грудь: 590 мм, Талия: 520 мм, Бёдра: 620 мм',
        price: 220,
        imageSrc: '/manekeny-portnovskie/tors-td-103.jpg',
    },
    {
        title: 'Манекен ноги женской объёмный',
        description: 'Объёмная форма',
        size: 'Материал: пластик',
        price: 372,
        imageSrc: '/manekeny-portnovskie/maneken-noga-zhenskaya.jpg',
    },
    {
        title: 'Торс женский «Люся»',
        description: 'Арт: «Люся»',
        size: 'Материал: пластик',
        price: 130,
        imageSrc: '/manekeny-portnovskie/tors-lucya.jpg',
    },
    {
        title: 'Торс женский «Памела»',
        description: 'Арт: «Памела»',
        size: 'Материал: пластик',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/manekeny-portnovskie/tors-pamela.jpg',
    },
    {
        title: 'Вешало для одежды (под заказ)',
        description: 'Изготовление по запросу',
        size: 'Конфигурация согласовывается индивидуально',
        price: null,
        priceLabel: 'Под заказ',
        imageSrc: '/manekeny-portnovskie/veshalo-dlya-odezhdy.jpg',
    },
    {
        title: 'Манекен портновский женский',
        description: 'Настольное исполнение',
        size: 'Материал: текстиль / ППУ',
        price: 1220,
        imageSrc: '/manekeny-portnovskie/maneken-portnovskiy-zhenskiy.jpg',
    },
    {
        title: 'Манекен портновский женский / мужской',
        description: 'На регулируемой подставке',
        size: 'Высота регулируется',
        price: 2100,
        imageSrc:
            '/manekeny-portnovskie/maneken-portnovskiy-zhenskiy-muzhskoy.jpg',
    },
    {
        title: 'Манекен портновский детский',
        description: 'Регулируемая стойка',
        size: 'Размер детский',
        price: 1100,
        imageSrc: '/manekeny-portnovskie/maneken-portnovskiy-detskiy.jpg',
    },
    {
        title: 'Рука манекена D1 глянцевая',
        description: 'Пластиковый манекен',
        size: 'Материал: пластик',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/manekeny-portnovskie/ruka-d1.jpg',
    },
    {
        title: 'Рука манекена D3 телесная',
        description: 'Пластиковый манекен',
        size: 'Материал: пластик телесный',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/manekeny-portnovskie/ruka-d3.jpg',
    },
];

