import type { Product } from '@/entities/product';

export const BASIS_PRODUCTS: Product[] = [
    {
        title: 'Стойка перфорированная L=1500 мм',
        description: 'Basis. Размер сечения: 40х40 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-stoyka.png',
        price: 1470,
    },
    {
        title: 'Стойка перфорированная L=1500 мм',
        description: 'Basis. Размер сечения: 40х40 мм. Цвет: сильвер/чёрный/белый',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-stoyka.png',
        price: null,
    },
    {
        title: 'Стойка перфорированная L=2400 мм',
        description: 'Basis. Размер сечения: 40х40 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-stoyka.png',
        price: 2569,
    },
    {
        title: 'Стойка перфорированная L=2400 мм',
        description: 'Basis. Размер сечения: 40х40 мм. Цвет: сильвер/чёрный/белый',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-stoyka.png',
        price: null,
    },
    {
        title: 'Стойка перфорированная L=2975 мм',
        description: 'Basis. Размер сечения: 40х40 мм. Цвет: сильвер',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-stoyka.png',
        price: null,
    },
    {
        title: 'Стойка перфорированная PP L=2400 мм',
        description: 'Двойная перфорация. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-stoyka-pp.png',
        price: 943,
    },
    {
        title: 'Держатель для стекла (пара)',
        description: 'TP21 (без упора). Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp21-tp21a.png',
        price: 383,
    },
    {
        title: 'Держатель для стекла (пара)',
        description: 'TP21a (с упором). Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp21-tp21a.png',
        price: 465,
    },
    {
        title: 'Держатель для панели (штука)',
        description: 'TP22 (без упора)',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp22-tp20.png',
        price: null,
    },
    {
        title: 'Держатель для панели (штука)',
        description: 'TP20 (с упором). Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp22-tp20.png',
        price: 263,
    },
    {
        title: 'Держатель для панели с фиксацией, съёмный (пара, лев.+прав.)',
        description: 'TP22-1. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp22-1.png',
        price: 330,
    },
    {
        title: 'Держатель для панели с фиксацией (пара, лев.+прав.)',
        description: 'TP22a (без упора). Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp22a.png',
        price: 330,
    },
    {
        title: 'Заглушка пластиковая',
        description: 'TP2',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp2.png',
        price: 48,
    },
    {
        title: 'Ножка пластиковая',
        description: 'TP5',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp5.png',
        price: 38,
    },
    {
        title: 'Втулка внутренняя',
        description: 'TP3',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp3.png',
        price: 89,
    },
    {
        title: 'Ножка завинчивающаяся',
        description: 'TP4',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp4.png',
        price: 74,
    },
    {
        title: 'Опора односторонняя',
        description: 'ТР7. L=420 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp7.jpg',
        price: 1170,
    },
    {
        title: 'Опора двухсторонняя',
        description: 'ТР9. L=640 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp9.jpg',
        price: 1380,
    },
    {
        title: 'Крепеж к стене регулируемый',
        description: 'ТР14. L=210-315 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp14.jpg',
        price: 395,
    },
    {
        title: 'Стяжка',
        description: 'ТР17. L=600 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp17.jpg',
        price: 660,
    },
    {
        title: 'Стяжка',
        description: 'ТР17. L=900 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp17.jpg',
        price: 695,
    },
    {
        title: 'Стяжка',
        description: 'ТР17. L=1200 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp17.jpg',
        price: 870,
    },
    {
        title: 'Крепеж к стене фиксированный',
        description: 'ТР15. L=50 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp15.jpg',
        price: 283,
    },
    {
        title: 'Полкодержатель для стеклянных (8-10 мм) полок (пара)',
        description: 'ТР23b-1. L=100 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp23b-1.png',
        price: 399,
    },
    {
        title: 'Полкодержатель Г-образный (пара)',
        description: 'ТР23. L=200 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp23.jpg',
        price: 399,
    },
    {
        title: 'Полкодержатель Г-образный (пара)',
        description: 'ТР23. L=300 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp23.jpg',
        price: 462,
    },
    {
        title: 'Полкодержатель Г-образный (пара)',
        description: 'ТР23. L=400 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp23.jpg',
        price: 570,
    },
    {
        title: 'Полкодержатель для стеклянных полок (пара)',
        description: 'ТР23b. L=200 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp23b.jpg',
        price: 646,
    },
    {
        title: 'Полкодержатель внутренний (пара)',
        description: 'ТР41. L=300 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp41.jpg',
        price: 358,
    },
    {
        title: 'Кронштейн П-образный',
        description: 'ТР47. L=600 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp47.jpg',
        price: 980,
    },
    {
        title: 'Кронштейн П-образный',
        description: 'ТР47. L=900 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp47.jpg',
        price: 982,
    },
    {
        title: 'Кронштейн П-образный',
        description: 'ТР47. L=1200 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp47.jpg',
        price: 1215,
    },
    {
        title: 'Кронштейн фронтальный',
        description: 'ТР44. L=600 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp44.jpg',
        price: 730,
    },
    {
        title: 'Кронштейн фронтальный',
        description: 'ТР44. L=900 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp44.jpg',
        price: 690,
    },
    {
        title: 'Кронштейн фронтальный',
        description: 'ТР44. L=1200 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp44.jpg',
        price: 840,
    },
    {
        title: 'Кронштейн прямой на планку',
        description: 'ТР69. L=300 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp69.jpg',
        price: 192,
    },
    {
        title: 'Кронштейн прямой на стойку',
        description: 'ТР70. L=300 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp70.jpg',
        price: 194,
    },
    {
        title: 'Кронштейн фронтальный Т-образный на стойку',
        description: 'ТР40. 300×595 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp40.png',
        price: 815,
    },
    {
        title: 'Кронштейн наклонный с 7-ю штырьками на планку',
        description: 'ТР72. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp72.jpg',
        price: 321,
    },
    {
        title: 'Кронштейн наклонный с 7-ю штырьками на стойку',
        description: 'ТР73. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp73.jpg',
        price: 283,
    },
    {
        title: 'Крючок на планку',
        description: 'ТР52. L=100 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp52.jpg',
        price: 41,
    },
    {
        title: 'Крючок на планку',
        description: 'ТР52. L=150 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp52.jpg',
        price: 48,
    },
    {
        title: 'Крючок на планку',
        description: 'ТР52. L=200 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp52.jpg',
        price: 51,
    },
    {
        title: 'Крючок на планку',
        description: 'ТР52. L=250 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp52.jpg',
        price: 61,
    },
    {
        title: 'Крючок на стойку',
        description: 'ТР53. L=100 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp53.jpg',
        price: 43,
    },
    {
        title: 'Крючок на стойку',
        description: 'ТР53. L=150 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp53.jpg',
        price: 45,
    },
    {
        title: 'Крючок на стойку',
        description: 'ТР53. L=200 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp53.jpg',
        price: 52,
    },
    {
        title: 'Крючок на стойку',
        description: 'ТР53. L=250 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp53.jpg',
        price: 58,
    },
    {
        title: 'Кронштейн двухуровневый на планку',
        description: 'ТР75. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp75.jpg',
        price: 399,
    },
    {
        title: 'Кронштейн двухуровневый на стойку',
        description: 'ТР76. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp76.jpg',
        price: 562,
    },
    {
        title: 'Кронштейн наклонный с 5-ю крючками на планку',
        description: 'ТР66. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp66.jpg',
        price: 295,
    },
    {
        title: 'Кронштейн наклонный с 5-ю крючками на стойку',
        description: 'ТР67. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp67.jpg',
        price: 345,
    },
    {
        title: 'Кронштейн Зиг-Заг',
        description: 'ТР93. L=900 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp93.jpg',
        price: 957,
    },
    {
        title: 'Кронштейн Зиг-Заг',
        description: 'ТР93. L=1200 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp93.jpg',
        price: 1116,
    },
    {
        title: 'Кронштейн для шляп на планку',
        description: 'ТР118. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp118.jpg',
        price: 237,
    },
    {
        title: 'Кронштейн двойной',
        description: 'ТР48. (600+600 мм). Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp48.png',
        price: 1450,
    },
    {
        title: 'Кронштейн П-образный с опорами под полки',
        description: 'ТР49. Глубина 340 мм, L=600 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp49.png',
        price: 1248,
    },
    {
        title: 'Кронштейн П-образный с опорами под полки',
        description: 'ТР49. Глубина 340 мм, L=900 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp49.png',
        price: 1338,
    },
    {
        title: 'Кронштейн П-образный с опорами под полки',
        description: 'ТР49. Глубина 340 мм, L=1200 мм. Цвет: хром',
        imageSrc: '/trubi-i-stoyki/sistemy-basis-i-slim/basis-tp49.png',
        price: 1620,
    },
];

