import type { Product } from '@/entities/product';

export const AKSESSUARY_RAZNYE: Product[] = [
    {
        title: 'Вешалка для поясов и галстуков',
        description: 'Арт: F 116\nL=300 мм, хром',
        price: 105,
        imageSrc: '/ekonompaneli/aksessuary/raznye/f-116.jpg',
    },
    {
        title: 'Вешалка для сумок',
        description: 'Арт: F 122\nХром',
        price: 189,
        imageSrc: '/ekonompaneli/aksessuary/raznye/f-122.jpg',
    },
    {
        title: 'Полка для колготок',
        description: 'Арт: ЕК 360\nЦинк',
        price: 45,
        imageSrc: '/ekonompaneli/aksessuary/raznye/ek-360.jpg',
    },
    {
        title: 'Подставка для чулок',
        description: 'Арт: F119-15/c\nХром',
        price: 470,
        imageSrc: '/ekonompaneli/aksessuary/raznye/f119-150-c.jpg',
    },
    {
        title: 'Полка для рубашек',
        description: 'Арт: F 119\nХром',
        price: 215,
        imageSrc: '/ekonompaneli/aksessuary/raznye/f-119.jpg',
    },
    {
        title: 'Подставка для сорочек',
        description: 'Арт: F 119-8\n426×160×236 мм, хром',
        price: 535,
        imageSrc: '/ekonompaneli/aksessuary/raznye/f-119-8.jpg',
    },
    {
        title: 'Держатель для мячей',
        description: 'Арт: F 507\nL=100 мм, d=130 мм, хром',
        price: 95,
        imageSrc: '/ekonompaneli/aksessuary/raznye/f-507.jpg',
    },
    {
        title: 'Кронштейн для коньков',
        description: 'Арт: F 508\nХром',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/ekonompaneli/aksessuary/raznye/f-508.jpg',
    },
    {
        title: 'Полка универсальная',
        description: 'Арт: A 192\n600×240 мм',
        price: 250,
        imageSrc: '/ekonompaneli/aksessuary/raznye/a-192.jpg',
    },
    {
        title: 'Полка для обуви (прямая)',
        description: 'Арт: A 141\n250×100 мм',
        price: 43,
        imageSrc: '/ekonompaneli/aksessuary/raznye/a-141.jpg',
    },
    {
        title: 'Полка для обуви (с ценником)',
        description: 'Арт: A 143\n250×100 мм',
        price: 65,
        imageSrc: '/ekonompaneli/aksessuary/raznye/a-143.jpg',
    },
    {
        title: 'Полка для обуви (поворотная)',
        description: 'Арт: A 130\n230×70 мм, опора каблук/мысок',
        price: 51,
        imageSrc: '/ekonompaneli/aksessuary/raznye/a-130.jpg',
    },
    {
        title: 'Полка',
        description: 'Арт: F 138\n305×150 мм',
        price: 80,
        imageSrc: '/ekonompaneli/aksessuary/raznye/f-138.jpg',
    },
    {
        title: 'Полка с ценником',
        description: 'Арт: F 138-2\n305×150 мм',
        price: 85,
        imageSrc: '/ekonompaneli/aksessuary/raznye/f-138-2.jpg',
    },
    {
        title: 'Полка с опорами',
        description: 'Арт: F 191\nL=490 мм',
        price: 335,
        imageSrc: '/ekonompaneli/aksessuary/raznye/f-191.jpg',
    },
    {
        title: 'Полка прозрачная',
        description: 'Арт: F 194/P\n300×330 мм (Ш×Г), пластик',
        price: 133,
        imageSrc: '/ekonompaneli/aksessuary/raznye/f-194-p.jpg',
    },
    {
        title: 'Держатель для очков',
        description: 'Арт: F 512\nХром',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/ekonompaneli/aksessuary/raznye/f-512.jpg',
    },
    {
        title: 'Подставка для шляп (консоль)',
        description: 'd=80/100 мм, хром',
        price: 92,
        imageSrc: '/ekonompaneli/aksessuary/raznye/konsol-dlya-shlyap.jpg',
    },
    {
        title: 'Подставка для шляп (консоль)',
        description: 'd=140 мм, хром',
        price: 126,
        imageSrc: '/ekonompaneli/aksessuary/raznye/konsol-dlya-shlyap.jpg',
    },
    {
        title: 'Подставка под шляпу',
        description: 'Арт: F 17\nПластик (чёрный)',
        price: 77,
        imageSrc: '/ekonompaneli/aksessuary/raznye/f-17.jpg',
    },
    {
        title: 'Подставка под шляпу (детская)',
        description: 'Арт: F 17 детская\nПластик (чёрный)',
        price: 72,
        imageSrc: '/ekonompaneli/aksessuary/raznye/f-17-detskaya.jpg',
    },
    {
        title: 'Корзина маленькая',
        description: 'Арт: F 198\n300×300×200 мм, хром\n390×300×200 мм, хром',
        price: 790,
        imageSrc: '/ekonompaneli/aksessuary/raznye/f-198.jpg',
    },
    {
        title: 'Корзина большая',
        description: 'Арт: F 199\n610×300×150 мм, хром',
        price: 890,
        imageSrc: '/ekonompaneli/aksessuary/raznye/f-199.jpg',
    },
    {
        title: 'Полка-контейнер',
        description: 'Арт: F 361\n150×150 мм',
        price: 230,
        imageSrc: '/ekonompaneli/aksessuary/raznye/f-361.jpg',
    },
    {
        title: 'Полка-контейнер',
        description: 'Арт: F 360\n200×200 мм',
        price: 295,
        imageSrc: '/ekonompaneli/aksessuary/raznye/f-360.jpg',
    },
    {
        title: 'Полка наклонная',
        description: 'Арт: F 189\n240×350 мм',
        price: 143,
        imageSrc: '/ekonompaneli/aksessuary/raznye/f-189.jpg',
    },
    {
        title: 'Держатель формата A4',
        description: 'Арт: ЕК 362\nМатериал: сталь с покрытием цинка',
        price: 40,
        imageSrc: '/ekonompaneli/aksessuary/raznye/ek-362.jpg',
    },
    {
        title: 'Консоль для шляп (цинк)',
        description: 'Цинк',
        price: 25,
        imageSrc: '/ekonompaneli/aksessuary/raznye/konsol-dlya-shlyap.jpg',
    },
    {
        title: 'Корзина-накопитель',
        description: 'Арт: A196/h180\nКорзина 200×240×180 мм, хром',
        price: 370,
        imageSrc: '/ekonompaneli/aksessuary/raznye/a-196.jpg',
    },
];
