import type { Product } from '@/entities/product';

export const PRILAVKI: Product[] = [
    {
        title: 'Кассовый прилавок МКС-01',
        description: 'Арт: МКС-01\nДве полки',
        size: '1200 × 600 × 1100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/mks-01.png',
    },
    {
        title: 'Кассовый стол МКСВ-01',
        description: 'Арт: МКСВ-01\nТри полки, вырез под кассу',
        size: '1200 × 600 × 1100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/mksv-01.png',
    },
    {
        title: 'Угловой прилавок ММУ-01',
        description: 'Арт: ММУ-01',
        size: '600 × 600 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/mmu-01.png',
    },
    {
        title: 'Прилавок МПУ-01',
        description: 'Арт: МПУ-01\nОдна полка',
        size: '600 × 600 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/mpu-01.png',
    },
    {
        title: 'Прилавок МПУ-02',
        description: 'Арт: МПУ-02\nДве полки',
        size: '600 × 600 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/mpu-02.png',
    },
    {
        title: 'Прилавок МПУ-03',
        description: 'Арт: МПУ-03\nЧетыре выдвижных ящика',
        size: '600 × 600 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/mpu-03.png',
    },
    {
        title: 'Прилавок МПУ-04',
        description: 'Арт: МПУ-04\nВыдвижной ящик + полка',
        size: '600 × 600 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/mpu-04.png',
    },
    {
        title: 'Прилавок МПУ-05',
        description: 'Арт: МПУ-05\nПолка + дверца',
        size: '600 × 600 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/mpu-05.png',
    },
    {
        title: 'Прилавок МПУ-06',
        description: 'Арт: МПУ-06\nВыдвижной ящик + полка + дверца',
        size: '600 × 600 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/mpu-06.png',
    },
    {
        title: 'Прилавок МПШ-01',
        description: 'Арт: МПШ-01\nДве полки',
        size: '1200 × 600 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/mpsh-01.png',
    },
    {
        title: 'Прилавок МПШ-02',
        description: 'Арт: МПШ-02\nЧетыре полки',
        size: '1200 × 600 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/mpsh-02.png',
    },
    {
        title: 'Прилавок МПШ-03',
        description: 'Арт: МПШ-03\nВосемь выдвижных ящиков',
        size: '1200 × 600 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/mpsh-03.png',
    },
    {
        title: 'Прилавок МПШ-04',
        description: 'Арт: МПШ-04\nЧетыре ящика + полка',
        size: '1200 × 600 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/mpsh-04.png',
    },
    {
        title: 'Прилавок МПШ-05',
        description: 'Арт: МПШ-05\nЧетыре ящика + полка + дверца',
        size: '1200 × 600 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/mpsh-05.png',
    },
    {
        title: 'Прилавок МПШ-06',
        description: 'Арт: МПШ-06\nДве полки + две дверцы',
        size: '1200 × 600 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/mpsh-06.png',
    },
    {
        title: 'Прилавок МПШ-07',
        description: 'Арт: МПШ-07\nДва ящика + две полки',
        size: '1200 × 600 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/mpsh-07.png',
    },
    {
        title: 'Прилавок-горка ПМ-21',
        description: 'Арт: ПМ-21\nДве полки, накопитель',
        size: '800 × 400 × 1200 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-21.jpg',
    },
    {
        title: 'Прилавок-горка ПМ-22',
        description: 'Арт: ПМ-22\nТри полки, накопитель',
        size: '800 × 400 × 1200 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-22.jpg',
    },
    {
        title: 'Прилавок-горка ПМ-23',
        description: 'Арт: ПМ-23\nТри наклонные полки, накопитель',
        size: '800 × 400 × 1200 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-23.jpg',
    },
    {
        title: 'Прилавок-горка ПМ-24',
        description: 'Арт: ПМ-24\nНаклонные полки ячейки, накопитель',
        size: '800 × 400 × 1200 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-24.jpg',
    },
    {
        title: 'Прилавок-горка угловой ПМ-25',
        description: 'Арт: ПМ-25\nДве стеклянные полки, накопитель',
        size: '800 × 800 × 1200 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-25.jpg',
    },
    {
        title: 'Прилавок ПМ-30',
        description:
            'Арт: ПМ-30\nРаспашные дверцы ЛДСП и стекло, в накопителе полка',
        size: '900 × 450 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-30.jpg',
    },
    {
        title: 'Прилавок ПМ-31',
        description: 'Арт: ПМ-31\nСтеклянные дверцы, накопитель открытый',
        size: '900 × 450 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-31.jpg',
    },
    {
        title: 'Прилавок угловой ПМ-31У',
        description: 'Арт: ПМ-31У\nБез дверок',
        size: '750 × 750 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-31u.jpg',
    },
    {
        title: 'Прилавок угловой ПМ-31У-2',
        description: 'Арт: ПМ-31У-2\nБез дверок',
        size: '750 × 750 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-31u-2.jpg',
    },
    {
        title: 'Прилавок глухой рабочий ПМ-32',
        description: 'Арт: ПМ-32',
        size: '500 × 450 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-32.jpg',
    },
    {
        title: 'Прилавок рабочий ПМ-33',
        description: 'Арт: ПМ-33\nЯщики выдвижные, накопитель с полкой.',
        size: '900 × 450 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-33.jpg',
    },
    {
        title: 'Прилавок угловой ПМ-34',
        description: 'Арт: ПМ-34\nУгол внутренний',
        size: '700 × 700 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-34.jpg',
    },
    {
        title: 'Прилавок-витрина стеклянный ПМ-35',
        description:
            'Арт: ПМ-35\nНизкая витрина, дверцы и полки стеклянные, топ стекло',
        size: '800 × 350 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-35.jpg',
    },
    {
        title: 'Витрина напольная стеклянная ПМ-36',
        description: 'Арт: ПМ-36\nЗадняя стенка зеркало, полки и дверцы стекло',
        size: '800 × 400 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-36.jpg',
    },
    {
        title: 'Прилавок наклонный ПМ-37',
        description: 'Арт: ПМ-37\nБез дверок',
        size: '900 × 500 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-37.jpg',
    },
    {
        title: 'Прилавок угловой наклонный ПМ-37А',
        description: 'Арт: ПМ-37А\nБез дверок',
        size: '800 × 800 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-37a.jpg',
    },
    {
        title: 'Прилавок угловой наклонный ПМ-37Б',
        description: 'Арт: ПМ-37Б\nВнутренний угол, без дверок',
        size: '800 × 800 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-37b.jpg',
    },
    {
        title: 'Тумба-прилавок откатная наклонная ПМ-38',
        description: 'Арт: ПМ-38',
        size: '600 × 350 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-38.jpg',
    },
    {
        title: 'Прилавок наклонный угловой ПМ-39',
        description: 'Арт: ПМ-39\nВнутренний угол, полка под сумку',
        size: '750 × 750 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-39.jpg',
    },
    {
        title: 'Прилавок-витрина горка ПМ-41',
        description: 'Арт: ПМ-41\nДве полки, накопитель',
        size: '800 × 400 × 1200 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-41.jpg',
    },
    {
        title: 'Прилавок-витрина горка ПМ-42',
        description: 'Арт: ПМ-42\nТри полки, накопитель',
        size: '800 × 400 × 1200 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-42.jpg',
    },
    {
        title: 'Прилавок-витрина горка ПМ-43',
        description:
            'Арт: ПМ-43\n12 ячеек, полки ДСП, перегородки стекло, накопитель',
        size: '800 × 400 × 1200 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-43.jpg',
    },
    {
        title: 'Прилавок-витрина горка кондитерская ПМ-44',
        description:
            'Арт: ПМ-44\n28 ячеек, полки ДСП, перегородки стекло, накопитель',
        size: '800 × 400 × 1200 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-44.jpg',
    },
    {
        title: 'Прилавок-витрина горка угловая ПМ-45',
        description: 'Арт: ПМ-45\nДве полки, накопитель',
        size: '800 × 800 × 1200 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-45.jpg',
    },
    {
        title: 'Прилавок-витрина горка ПМ-46',
        description: 'Арт: ПМ-46\nТри полки, накопитель',
        size: '800 × 800 × 1200 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-46.jpg',
    },
    {
        title: 'Прилавок-витрина горка угловая ПМ-47',
        description: 'Арт: ПМ-47\nУгол 120 градусов',
        size: '600 × 600 × 1200 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-47.jpg',
    },
    {
        title: 'Прилавок-витрина горка угловая ПМ-48',
        description: 'Арт: ПМ-48\nУгол 135 градусов',
        size: '700 × 700 × 1200 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-48.jpg',
    },
    {
        title: 'Прилавок-витрина горка угловая ПМ-49',
        description: 'Арт: ПМ-49\nУгол 90 градусов внутренний',
        size: '800 × 800 × 1200 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/pm-49.jpg',
    },

    {
        title: 'Прилавок с экономпанелью СП-04',
        description: 'Арт: СП-04\nРаспашные стеклянные и ЛДСП дверцы',
        size: '800 × 400 × 1050 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/sp-4.jpg',
    },
    {
        title: 'Прилавок стеклянный СП-05',
        description:
            'Арт: СП-05\nСтеклянные и ДСП (в накопителе) распашные дверцы',
        size: '800 × 400 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/sp-5.jpg',
    },
    {
        title: 'Стеклянный торговый прилавок СП-06',
        description:
            'Арт: СП-06\nРаздвижные дверцы (стеклянные и ДСП в накопителе)',
        size: '700 × 400 × 1000 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/sp-06.jpg',
    },
    {
        title: 'Витрина-прилавок пристенная СП-08',
        description:
            'Арт: СП-08\nДве стеклянные полки лесенкой, накопитель с полкой',
        size: '800 × 400 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/sp-08.jpg',
    },
    {
        title: 'Витрина-прилавок СП-09',
        description: 'Арт: СП-09\nРаспашные дверцы, выдвижной ящик',
        size: '800 × 400 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/sp-09.jpg',
    },
    {
        title: 'Кассовый прилавок СП-10',
        description: 'Арт: СП-10\nЗащита из стекла, выдвижной ящик',
        size: '500 × 450 × 1250 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/sp-10.jpg',
    },
    {
        title: 'Прилавок ювелирный СПЮ-01',
        description: 'Арт: СПЮ-01\nВыдвижная выставочная часть',
        size: '800 × 400 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/prilavki-iz-ldsp/spy-01.jpg',
    },
];
