import type { Product } from '@/entities/product';

export const STEKLYANNYE_VITRINY: Product[] = [
    {
        title: 'Витрина из профиля ПР-03',
        description: 'Арт: ПР-03\nНакопитель, задняя стенка стекло, топ ЛДСП',
        size: '900 × 400 × 2100 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-03.jpg',
    },
    {
        title: 'Витрина из профиля ПР-03А',
        description: 'Арт: ПР-03А\nНакопитель, задняя стенка зеркало, топ ЛДСП',
        size: '900 × 400 × 2100 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-03a.jpg',
    },
    {
        title: 'Витрина из профиля ПР-04',
        description: 'Арт: ПР-04\nНакопитель, фриз, задняя стенка зеркало',
        size: '900 × 400 × 2100 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-04.jpg',
    },
    {
        title: 'Витрина из профиля ПР-05',
        description:
            'Арт: ПР-05\nС доп. обвязкой из профиля, 4 стеклянные дверцы',
        size: '900 × 400 × 2100 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-05.jpg',
    },
    {
        title: 'Витрина из профиля ПР-06',
        description: 'Арт: ПР-06\nНакопитель, топ – ЛДСП',
        size: '500 × 500 × 2100 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-06.jpg',
    },
    {
        title: 'Витрина из профиля ПР-07',
        description: 'Арт: ПР-07\nДоп. обвязка, задняя стенка зеркало',
        size: '500 × 500 × 2100 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-07.jpg',
    },
    {
        title: 'Витрина из профиля ПР-09',
        description: 'Арт: ПР-09\nЗадняя стенка зеркало, доп. обвязка профилем',
        size: '900 × 350 × 2100 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-09.jpg',
    },
    {
        title: 'Витрина из профиля ПР-10А',
        description:
            'Арт: ПР-10А\nЗадняя стенка ДСП, доп. обвязка, четыре распашные стеклянные дверцы',
        size: '900 × 400 × 2100 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-10a.png',
    },
    {
        title: 'Витрина из профиля ПР-11',
        description: 'Арт: ПР-11\nБез дверок, задняя стенка стекло',
        size: '900 × 350 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-11jpg.jpg',
    },
    {
        title: 'Витрина из профиля ПР-11А',
        description: 'Арт: ПР-11А\nБез дверок, задняя стенка зеркало',
        size: '900 × 400 × 2100 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-11a.jpg',
    },
    {
        title: 'Витрина из профиля ПР-12',
        description: 'Арт: ПР-12\nВсе дверцы – раздвижные',
        size: '900 × 400 × 2100 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-12.jpg',
    },

    {
        title: 'Витрина из профиля двойная ПР-15',
        description:
            'Арт: ПР-15\nЗадняя стенка зеркало, дверцы распашные. Профиль анодированный, накопитель h500mm.',
        size: '1100 × 350 × 2100 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-15.jpg',
    },
    {
        title: 'Витрина из профиля двойная ПР-15А',
        description:
            'Арт: ПР-15А\nЗадняя стенка зеркало, по две стеклянные дверцы в секции',
        size: '1500 × 350 × 2100 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-15a.jpg',
    },
    {
        title: 'Витрина из профиля двойная ПР-15Б',
        description:
            'Арт: ПР-15Б\nЗадняя стенка ДСП, стеклянные полки и раздвижные дверцы',
        size: '1800 × 350 × 2100 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-15b.png',
    },
    {
        title: 'Витрина из профиля тройная ПР-16',
        description: 'Арт: ПР-16\nТри секции, задняя стенка зеркало',
        size: '1500 × 350 × 2100 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-16.jpg',
    },
    {
        title: 'Витрина из профиля тройная ПР-16А',
        description:
            'Арт: ПР-16А\nДоп. обвязка из профиля, сзади зеркало, все дверцы распашные',
        size: '2200 × 350 × 2100 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-16a.jpg',
    },
    {
        title: 'Витрина стеклянная из профиля ПР-17',
        description:
            'Арт: ПР-17\nДвухсекционная, все стенки стекло, дверцы распашные, топ и низ – ЛДСП',
        size: '1500 × 350 × 2000 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-17.jpg',
    },
    {
        title: 'Витрина из профиля угловая ПР-20',
        description:
            'Арт: ПР-20\n5-гранная, дверца распашная, накопитель, топ ЛДСП',
        size: '600 × 600 × 2100 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-20.jpg',
    },
    {
        title: 'Витрина из профиля угловая ПР-21',
        description: 'Арт: ПР-21\n5-гранная, стенки стекло, фриз и накопитель',
        size: '800 × 800 × 2100 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-21.jpg',
    },
    {
        title: 'Витрина из профиля шестигранная ПР-23',
        description: 'Арт: ПР-23\nНакопитель, топ ЛДСП, стенки и дверца стекло',
        size: '650 × 650 × 2000 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-23.jpg',
    },
    {
        title: 'Витрина профильная шестигранная ПР-24',
        description:
            'Арт: ПР-24\nСтенки выставочной части стеклянные, фриз и накопитель ДСП',
        size: '650 × 650 × 2000 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-24.jpg',
    },
    {
        title: 'Витрина профильная шестигранная ПР-25',
        description:
            'Арт: ПР-25\nЗадняя стенка зеркало, топ ЛДСП, две дверцы стеклянные',
        size: '800 × 800 × 2000 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-25.jpg',
    },
    {
        title: 'Витрина профильная шестигранная ПР-26',
        description:
            'Арт: ПР-26\nСтенки стекло, фриз и накопитель ЛДСП, доп. обвязка из профиля',
        size: '800 × 800 × 2000 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-26.jpg',
    },
    {
        title: 'Витрина профильная навесная ПР-40',
        description:
            'Арт: ПР-40\nЗадняя стенка зеркало, распашные дверцы и полки стеклянные',
        size: '750 × 110 × 750 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-40.jpg',
    },
    {
        title: 'Стенд навесной из профиля ПР-41',
        description: 'Арт: ПР-41\nСтеклянные дверцы, задняя стенка ЛДСП',
        size: '750 × 110 × 750 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/pr-41.jpg',
    },
    {
        title: 'Витрина ювелирная СПЮ-02',
        description:
            'Арт: СПЮ-02\nВ выставочной части дверцы раздвижные, в накопителе распашные, полка',
        size: '1300 × 350 × 1100 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/spy-02.jpg',
    },
    {
        title: 'Витрина ювелирная СПЮ-03',
        description:
            'Арт: СПЮ-03\nВ выставочной части дверцы раздвижные, 6 выдвижных ящиков',
        size: '1200 × 350 × 1100 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/spy-03.jpg',
    },
    {
        title: 'Торговая витрина СВ-13',
        description: 'Арт: СВ-13\nНакопитель, фриз',
        size: '800 × 400 × 2000 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/sv-13.jpg',
    },
    {
        title: 'Витрина-стеллаж с антрисолью СВ-14',
        description: 'Арт: СВ-14\nДва накопителя',
        size: '800 × 400 × 2000 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/sv-14.jpg',
    },
    {
        title: 'Витрина с ДСП-полкой СВ-17',
        description: 'Арт: СВ-17\nНакопитель, фриз',
        size: '900 × 500 × 2100 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/sv-17.jpg',
    },
    {
        title: 'Витрина навесная СВ-23',
        description: 'Арт: СВ-23\nСтеклянные дверцы, задняя стенка ДСП',
        size: '600 × 330 × 300 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/sv-23.png',
    },
    {
        title: 'Витрина навесная угловая СВ-25',
        description: 'Арт: СВ-25',
        size: '350 × 350 × 600 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/sv-25.jpg',
    },
    {
        title: 'Витрина навесная угловая СВ-26',
        description: 'Арт: СВ-26',
        size: '500 × 500 × 700 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/sv-26.jpg',
    },
    {
        title: 'Витрина навесная СВ-27',
        description: 'Арт: СВ-27\nРаспашные стеклянные дверцы',
        size: '500 × 250 × 700 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/sv-27.jpg',
    },
    {
        title: 'Витрина навесная СВ-27А',
        description: 'Арт: СВ-27А\nРаздвижные стеклянные дверцы',
        size: '500 × 250 × 700 мм',
        price: undefined,
        priceLabel: 'Цена по запросу',
        imageSrc: '/steklyannye-vitriny/sv-27a.jpg',
    },
];
