import type { Product } from '@/entities/product';

export const STELAZHI: Product[] = [
    {
        title: 'Стеллаж-витрина АС-02',
        description: 'Арт: АС-02\nВитрина для аптеки',
        size: '500 × 500 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/as-02.png',
    },
    {
        title: 'Кассовая витрина АСК-01',
        description: 'Арт: АСК-01\nКасса аптечного типа',
        size: '900 × 500 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/ask-01.png',
    },
    {
        title: 'Стеллаж с выдвижными ящиками АСР-01',
        description: 'Арт: АСР-01\n16 выдвижных ящиков',
        size: '800 × 500 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/asp-01.jpg',
    },
    {
        title: 'Стеллаж на хромированных трубах ОС-07',
        description:
            'Арт: ОС-07\nТрубы системы Joker (d=30mm), крепление фланцами',
        size: '2000 × 400 × 1708 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/os-07.png',
    },
    {
        title: 'Островной стенд обувной ОС-08',
        description: 'Арт: ОС-08\nСтенд для обуви, полки стекло, склейка',
        size: '900 × 900 × 1300 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/os-08.png',
    },
    {
        title: 'Стеллаж обувной ОС-12',
        description: 'Арт: ОС-12\nСтеллаж ЛДСП, квадратные полки',
        size: '800 × 800 × 1000 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/os-12.jpg',
    },
    {
        title: 'Стеллаж обувной ОС-13',
        description: 'Арт: ОС-13\nСтеклянный стеллаж на ДСП подиуме',
        size: '900 × 300 × 1200 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/os-13.jpg',
    },
    {
        title: 'Шкаф-витрина из профиля и ЛДСП ПР-27',
        description:
            'Арт: ПР-27\nЗадняя стенка зеркало, в накопителе две полки, дверцы распашные, топ ДСП',
        size: '800 × 300 × 2000 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/pr-27.jpg',
    },
    {
        title: 'Шкаф с ячейками (камера хранения) – 16 секций Р-02',
        description:
            'Арт: Р-02\nШкаф секционный (16 ячеек) с дверками для хранения сумок и вещей, для магазинов и супермаркетов',
        size: '1400 × 350 × 2000 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/p-02.jpg',
    },
    {
        title: 'Стеллаж Базис СБ-01',
        description: 'Арт: СБ-01\nРегулируемые стеклянные полки',
        size: '900 × 400 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/sb-01.jpg',
    },
    {
        title: 'Стеллаж пристенный на стойках СБ-02',
        description:
            'Арт: СБ-02\nСтойки Basis BS, полки стеклянные регулируемые по высоте, полкодержатели с ограничителями',
        size: '1200 × 400 × 1500 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/sb-02.png',
    },
    {
        title: 'Стеллаж пристенный на стойках СБ-03',
        description:
            'Арт: СБ-03\nСтойки Basis BS, полки стеклянные регулируемые по высоте, полкодержатели с ограничителями',
        size: '1550 × 400 × 1500 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/sb-03.png',
    },
    {
        title: 'Стеллаж пристенный на стойках СБ-04',
        description:
            'Арт: СБ-04\nСтойки Basis BS, полки стеклянные регулируемые по высоте, полкодержатели с ограничителями',
        size: '1800 × 400 × 1500 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/sb-04.png',
    },
    {
        title: 'Стеллаж на стойках Basis с накопителем СБ-05',
        description:
            'Арт: СБ-05\nПерфорированные стойки Basis 40×40 мм, полки стекло 150 мм, верхняя полка ЛДСП 300 мм',
        size: '1000 × 370 × 2200 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/sb-05.png',
    },
    {
        title: 'Торговый стеллаж-витрина СВ-01',
        description:
            'Арт: СВ-01\nРаздвижные стеклянные дверцы, полки стекло, накопитель',
        size: '900 × 400 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/sv-01.jpg',
    },
    {
        title: 'Стеллаж-витрина ювелирный СПЮ-04',
        description:
            'Арт: СПЮ-04\nФасады с фрезеровкой, задняя стенка зеркало, полки стекло',
        size: '900 × 350 × 2000 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/spy-04.jpg',
    },
    {
        title: 'Стеллаж открытый с накопителем СТ-01',
        description: 'Арт: СТ-01\nС накопителем',
        size: '900 × 500 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-01.jpg',
    },
    {
        title: 'Стеллаж для хлеба СТ-02',
        description: 'Арт: СТ-02\nНаклонные полки',
        size: '900 × 500 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-02.jpg',
    },
    {
        title: 'Стеллаж с ящиками СТ-03',
        description: 'Арт: СТ-03\nТри выдвижных ящика',
        size: '900 × 500 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-03.jpg',
    },
    {
        title: 'Стеллаж с накопителем СТ-04',
        description: 'Арт: СТ-04',
        size: '900 × 400 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-04.jpg',
    },
    {
        title: 'Стеллаж СТ-05',
        description: 'Арт: СТ-05',
        size: '1200 × 400 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-05.jpg',
    },
    {
        title: 'Стеллаж угловой СТ-06',
        description: 'Арт: СТ-06',
        size: '750 × 750 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-06.jpg',
    },
    {
        title: 'Стеллаж с наклонными полками СТ-07',
        description: 'Арт: СТ-07',
        size: '900 × 400 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-07.jpg',
    },
    {
        title: 'Стеллаж выставочный СТ-08',
        description: 'Арт: СТ-08\nЧетыре наклонные полки, фриз для навигации',
        size: '900 × 500 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-08.jpg',
    },
    {
        title: 'Стеллаж для продуктов СТ-09',
        description: 'Арт: СТ-09',
        size: '2100 × 450 × 2050 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-09.png',
    },
    {
        title: 'Стеллаж со стеклянными дверцами СТ-10',
        description: 'Арт: СТ-10\nПолки ЛДСП, выдвижные ящики',
        size: '750 × 500 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-10.png',
    },
    {
        title: 'Стеллаж СТ-11',
        description: 'Арт: СТ-11\nВыдвижной ящик',
        size: '700 × 350 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-11.png',
    },
    {
        title: 'Стеллаж СТ-12',
        description: 'Арт: СТ-12\nБез задней стенки',
        size: '600 × 350 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-12.png',
    },
    {
        title: 'Стеллаж низкий СТ-13',
        description: 'Арт: СТ-13',
        size: '600 × 250 × 900 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-13.png',
    },
    {
        title: 'Стеллаж выставочный СТ-16',
        description: 'Арт: СТ-16\nВитринные дверцы, полки ЛДСП',
        size: '800 × 350 × 2050 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-16.png',
    },
    {
        title: 'Стеллаж изогнутый СТ-17',
        description: 'Арт: СТ-17',
        size: '500 × 500 × 1800 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-17.png',
    },
    {
        title: 'Стеллаж декоративный СТ-18',
        description:
            'Арт: СТ-18\nПолки фиксированные, трубы металлические, крепление труб к стене',
        size: '1400 × 350 × 2550 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-18.png',
    },
    {
        title: 'Стенд-витрина стеклянный СТ-19',
        description:
            'Арт: СТ-19\nПолки стекло, трубы Master (хром, 25×25 мм), полкодержатели зажимные',
        size: '2025 × 400 × 1500 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-19.png',
    },
    {
        title: 'Стеллаж витринный СТ-20',
        description: 'Арт: СТ-20\n4 распашные дверцы',
        size: '800 × 400 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-20.jpg',
    },
    {
        title: 'Витрина-стеллаж СТ-21',
        description: 'Арт: СТ-21\nЗадняя стенка оргалит, стеклянные полки',
        size: '800 × 400 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-21.jpg',
    },
    {
        title: 'Витрина-стеллаж СТ-21А',
        description: 'Арт: СТ-21А\nВыступающий накопитель',
        size: '800 × 400 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-21a.jpg',
    },
    {
        title: 'Витрина-стеллаж СТ-22',
        description: 'Арт: СТ-22\nЗадняя стенка зеркало, полки стеклянные',
        size: '800 × 400 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-22.jpg',
    },
    {
        title: 'Витрина-стеллаж СТ-23',
        description: 'Арт: СТ-23\nЗадняя стенка – стекло, полки стеклянные',
        size: '800 × 400 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-23.jpg',
    },
    {
        title: 'Витрина-стеллаж СТ-27',
        description: 'Арт: СТ-27\nЗадняя стенка оргалит, высокий накопитель',
        size: '800 × 400 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-27.jpg',
    },
    {
        title: 'Витрина-стеллаж СТ-28',
        description:
            'Арт: СТ-28\nДве секции, сзади оргалит, дверцы стекло распашные',
        size: '800 × 400 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-28.jpg',
    },
    {
        title: 'Витрина-стеллаж СТ-29',
        description:
            'Арт: СТ-29\nДве секции, сзади оргалит, дверцы стекло раздвижные',
        size: '800 × 400 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-29.jpg',
    },
    {
        title: 'Стеллаж-витрина СТ-30',
        description:
            'Арт: СТ-30\nДве секции, задняя стенка стекло, полки стеклянные',
        size: '800 × 400 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-30.jpg',
    },
    {
        title: 'Витрина-стеллаж СТ-31',
        description: 'Арт: СТ-31\nЗадняя стенка стекло, накопитель и фриз',
        size: '800 × 400 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-31.jpg',
    },
    {
        title: 'Витрина-стеллаж СТ-32',
        description: 'Арт: СТ-32\nЗадняя стенка оргалит, накопитель и фриз',
        size: '800 × 400 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-32.jpg',
    },
    {
        title: 'Витрина-стеллаж СТ-33',
        description:
            'Арт: СТ-33\nДве секции, задняя стенка зеркало, полки стеклянные',
        size: '800 × 400 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-33.jpg',
    },
    {
        title: 'Витрина-стеллаж СТ-34',
        description: 'Арт: СТ-34\nДве секции, задняя стенка оргалит',
        size: '800 × 400 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-34.jpg',
    },
    {
        title: 'Витрина-стеллаж угловая СТ-35',
        description: 'Арт: СТ-35\nЗадняя стенка зеркало, полки стеклянные',
        size: '800 × 800 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-35.jpg',
    },
    {
        title: 'Витрина-стеллаж угловая СТ-36',
        description: 'Арт: СТ-36\nДве секции, задняя стенка ДСП, полки стекло',
        size: '800 × 800 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-36.jpg',
    },
    {
        title: 'Кассовая витрина-стеллаж СТ-37',
        description:
            'Арт: СТ-37\nОкошко с раздвижными стеклянными дверцами, полки стекло, накопитель',
        size: '1000 × 400 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-37.jpg',
    },

    {
        title: 'Витрина-пенал СТ-39',
        description: 'Арт: СТ-39\nДве секции, дверцы и полки стеклянные',
        size: '500 × 400 × 2000 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-39.jpg',
    },
    {
        title: 'Стеллаж для колготок СТ-40',
        description: 'Арт: СТ-40\nПерегородки из стекла, выдвижные ящики',
        size: '1000 × 350 × 2000 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-40.jpg',
    },

    {
        title: 'Стеллаж со стеклянными полками открытый СТ-44',
        description:
            'Арт: СТ-44\nБез дверок, полки стеклянные, крепятся на угловых стойках ЛДСП',
        size: '850 × 400 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/st-44.jpg',
    },
    {
        title: 'Стеллаж для бутылок СТА-01',
        description: 'Арт: СТА-01\n6 прямых полок, 8 наклонных',
        size: '900 × 500 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/sta-01.jpg',
    },
    {
        title: 'Стеллаж для бутылок СТА-02',
        description:
            'Арт: СТА-02\nВинный стеллаж, наклонные полки для алкогольной продукции',
        size: '900 × 303 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/sta-02.png',
    },
    {
        title: 'Стенд для смесителей СТД-01',
        description: 'Арт: СТД-01\n27 сквозных отверстий диаметром 24 мм',
        size: '616 × 1000 × 2000 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/std-01.png',
    },
    {
        title: 'Стеллаж для микроволновок СТД-02',
        description:
            'Арт: СТД-02\nТорговый стеллаж для демонстрации микроволновых печей',
        size: '605 × 500 × 2084 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/std-02.png',
    },
    {
        title: 'Стеллаж для посудомоечных машин СТД-03',
        description:
            'Арт: СТД-03\nДополнительное укрепление полок металлическими уголками',
        size: '637 × 600 × 1758 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/std-03.png',
    },
    {
        title: 'Стеллаж для духовок СТД-04',
        description:
            'Арт: СТД-04\nДополнительное укрепление полок, выдвижная секция на направляющих полного выдвижения',
        size: '650 × 528 × 2030 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/std-04.png',
    },
    {
        title: 'Стеллаж для журналов СТМ-01',
        description: 'Арт: СТМ-01',
        size: '900 × 500 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/stm-01.jpg',
    },
    {
        title: 'Стеллаж для оптики СТО-01',
        description: 'Арт: СТО-01\nСтойки для очков, зеркало',
        size: '900 × 350 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/sto-01.jpg',
    },
    {
        title: 'Стеллаж для продуктов СТП-01',
        description: 'Арт: СТП-01\nПерегородки из стекла',
        size: '900 × 350 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/stp-01.jpg',
    },
    {
        title: 'Стеллаж для продуктов СТП-02',
        description: 'Арт: СТП-02\nПерегородки из стекла',
        size: '900 × 350 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/stp-02.jpg',
    },
    {
        title: 'Стеллаж для продуктов СТП-03',
        description:
            'Арт: СТП-03\nПерегородки из стекла, задняя стенка зеркало',
        size: '900 × 350 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/stp-03.jpg',
    },
    {
        title: 'Стеллаж для продуктов СТП-04',
        description: 'Арт: СТП-04\nЗадняя стенка зеркало',
        size: '900 × 350 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/stp-04.jpg',
    },
    {
        title: 'Стеллаж для продуктов СТП-05',
        description:
            'Арт: СТП-05\nДля овощей или "сыпучки", перегородки из ДСП',
        size: '800 × 350 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/stp-05.jpg',
    },
    {
        title: 'Стеллаж с наклонными ячейками СТП-06',
        description:
            'Арт: СТП-06\nСтеллаж для продуктов, задние стенки ячеек зеркальные',
        size: '800 × 400 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/stp-06.jpg',
    },
    {
        title: 'Стеллаж-горка для овощей СТП-08',
        description: 'Арт: СТП-08\nЗадняя стенка ЛДСП',
        size: '900 × 500 × 1600 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/stp-08.jpg',
    },
    {
        title: 'Стеллаж-горка для овощей СТП-09',
        description: 'Арт: СТП-09\nБез задней стенки',
        size: '900 × 500 × 1600 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/stp-09.jpg',
    },
    {
        title: 'Стеллаж-горка для овощей СТП-10',
        description: 'Арт: СТП-10',
        size: '800 × 500 × 1000 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/stp-10.jpg',
    },
    {
        title: 'Стеллаж-горка для овощей СТП-11',
        description: 'Арт: СТП-11',
        size: '800 × 500 × 1600 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/stp-11.jpg',
    },
    {
        title: 'Стеллаж-горка для овощей СТП-12',
        description: 'Арт: СТП-12',
        size: '800 × 800 × 1600 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/stp-12.jpg',
    },
    {
        title: 'Стеллаж-горка для овощей СТП-13',
        description: 'Арт: СТП-13',
        size: '800 × 800 × 2000 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/stp-13.jpg',
    },
    {
        title: 'Стеллаж для хлеба и выпечки СТП-20',
        description:
            'Арт: СТП-20\nПолки с ограничителем из стекла, в накопителе полка',
        size: '900 × 500 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/stp-20jpg.jpg',
    },
    {
        title: 'Стеллаж для продуктов СТП-21',
        description:
            'Арт: СТП-21\nСтеллаж для сыпучки (конфет, орехов), перегородки и ограничители из стекла',
        size: '900 × 500 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/stp-21.jpg',
    },
    {
        title: 'Стеллаж ЛДСП универсальный СТП-22',
        description: 'Арт: СТП-22\nПолки ЛДСП, в накопителе полка',
        size: '900 × 500 × 2100 мм',
        price: null,
        priceLabel: 'Цена по запросу',
        imageSrc: '/stelazhi-iz-ldsp/stp-22.jpg',
    },
];
